#!/usr/bin/env php
<?php declare(strict_types=1);

//use \app\services\ServicesContainer;
use \Symfony\Component\Console\Application;
use \app\console\commands\UpdateCurrencyRates;
use \app\services\WhoopsService;

require __DIR__ . '/../../vendor/autoload.php';

//$di = new DI\Container();

$builder = new \DI\ContainerBuilder();
// $builder->enableCompilation(__DIR__ . '/tmp');
// $builder->writeProxiesToFile(true, __DIR__ . '/tmp/proxies');
$di = $builder->build();

$app = new Application('Currency Converter CLI', '1.0');
$app->addCommands([
    $di->get(UpdateCurrencyRates::class),
]);
$app->run();
