#!/usr/bin/env php
<?php

namespace app\console;

use DI\Container;
use \Symfony\Component\Console\Application;
use \app\console\commands\UpdateCurrencyRates;

require __DIR__ . '/../../vendor/autoload.php';

$di = new Container();

$app = new Application('Currency Converter CLI', '1.0');
$app->addCommands([
    $di->get(UpdateCurrencyRates::class),
]);
$app->run();
